baseurl = "/"
title = "My blog"
theme = "ghostwriter-master"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My Tech Blog"
    description = "A place to store what im learning and exploring in tech"
    github = "https://github.com/JonathanGreene888/"
    email = "jonathangreene888@gmail.com"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"